version: "3.5"
services:
  db:
    image: mongo
    hostname: db
    ports:
      - "27017:27017"
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "0.9GB"
    networks:
      - rinha-node

  cache:
    hostname: cache
    image: redis:latest
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: "0.04"
          memory: "0.5GB"
    networks:
      - rinha-node

  api1: # API - Instância 01
    image: lucasraziel/rinha-node:latest
    hostname: api1
    depends_on:
      - db
      - cache
    environment:
      - MONGO_URI=mongodb://db:27017
      - REDIS_PORT=6379
      - REDIS_HOST=cache
    ports:
      - "3002:3000"
    deploy:
      resources:
        limits:
          cpus: "0.37"
          memory: "0.5GB"
    networks:
      - rinha-node

  api2: # API - Instância 02
    image: lucasraziel/rinha-node:latest
    hostname: api2
    depends_on:
      - db
      - cache
    environment:
      - MONGO_URI=mongodb://db:27017
      - REDIS_PORT=6379
      - REDIS_HOST=cache
    ports:
      - "3001:3000"
    deploy:
      resources:
        limits:
          cpus: "0.37"
          memory: "0.5GB"
    networks:
      - rinha-node

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "0.2GB"
    networks:
      - rinha-node
networks:
  rinha-node:
