version: '3.5'
services:
  api1: # API - Instância 01
    image: gabrielleeg1/rinha:latest
    hostname: api1
    depends_on:
      - db
    environment:
      - PORT=80
      - HOST=api1
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=rinha
      - POSTGRES_PORT=5432
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  api2: # API - Instância 01
    image: gabrielleeg1/rinha:latest
    hostname: api2
    depends_on:
      - db
    environment:
      - PORT=80
      - HOST=api2
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=rinha
      - POSTGRES_PORT=5432
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  db: # Banco de dados
   image: postgres
   environment:
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'rinha'
   volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
   deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1.5GB'
