version: '3.5'
services:
  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.4GB'
  nats:
    hostname: nats
    image: nats:latest
    ports:
      - '4222:4222'
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.3GB'
  
  api01:
    image: andr3marra/rinha-api-2023
    hostname: rinha-api01
    depends_on:
      - db
      - nats
    environment:
      - DB_CONNECTION_STRING=Host=db;Username=admin;Password=123;Database=rinha;Connection Pruning Interval=1;Connection Idle Lifetime=2;Enlist=false;No Reset On Close=true
      - ASPNETCORE_URLS=http://+:80;http://+:81
      - DOTNET_TieredPGO=1
      - DOTNET_ReadyToRun=0
      - DOTNET_TC_QuickJitForLoops=1
      - NATS_URL=nats:4222
      - NATS_DESTINATION=api02
      - NATS_OWN=api01
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '0.9GB'
  
  api02:
    image: andr3marra/rinha-api-2023
    hostname: rinha-api02
    depends_on:
      - db
      - nats
    environment:
      - DB_CONNECTION_STRING=Host=db;Username=admin;Password=123;Database=rinha;Connection Pruning Interval=1;Connection Idle Lifetime=2;Enlist=false;No Reset On Close=true
      - ASPNETCORE_URLS=http://+:80;http://+:81
      - DOTNET_TieredPGO=1
      - DOTNET_ReadyToRun=0
      - DOTNET_TC_QuickJitForLoops=1
      - NATS_URL=nats:4222
      - NATS_DESTINATION=api01
      - NATS_OWN=api02
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '0.9GB'
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

networks:
  default:
    driver: bridge
    name: rinha