version: "3.5"
services:
  api1:
    hostname: api1
    restart: always
    image: camargodouglas/rinha_backend_go:latest
    pull_policy: always
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/rinha
      CACHE_URL: cache:6379
      PORT: 8080
      CPU_PROF: 
      MEM_PROF: 
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '512MB'
  api2:
    hostname: api2
    restart: always
    image: camargodouglas/rinha_backend_go:latest
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/rinha
      CACHE_URL: cache:6379
      PORT: 8080
      CPU_PROF:
      MEM_PROF:
    pull_policy: always
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '512MB'
  db:
    hostname: db
    restart: always
    image: postgres:15
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/postgres/:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rinha
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    command:
      ["postgres", "-c", "config_file=/docker-entrypoint-initdb.d/postgresql.conf"]
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1GB'
  cache:
    restart: always
    image: eqalpha/keydb
    hostname: cache
    ports:
      - "6380:6379"
    volumes:
      - ./scripts/keydb/keydb.conf:/etc/keydb/keydb.conf
    command: ["keydb-server", "/etc/keydb/keydb.conf"]
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '512MB'
  nginx:
    hostname: api
    restart: always
    image: nginx:1.15-alpine
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    volumes:
      - ./scripts/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '512MB'
volumes:
  postgres-data: